language: csharp
sudo: false
dist: trusty
dotnet: 2.1.300
mono:
  - latest
install:
- dotnet restore

script:
- dotnet build
- dotnet test ./test/CookieManager.Test/CookieManager.Test.csproj
os:
- linux
- osx
branches:
  only:
  - master
